name: VAT Calculator Test

on: [workflow_dispatch]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Setting display
        run: sudo apt-get install xvfb
      - name: Starting xvfb
        run: sudo Xvfb &
      - name: Build with Maven
        run: xvfb-run -a mvn clean install -DsuiteXmlFile=TestSuite.xml
